### ISSUE TITLE
Don't print banner on pscr when in -E or -D mode.

### ISSUE THREAD

**Issue by fullspectrumdev** [stealth/psc#2]
It might be nice, for scripting, to suppress the printing of the "banner" message when doing encoding/decoding of files, for easier/faster scripting.

```
 % ./pscsh -S scripting.socket -f script_/get_passwd 
unset HISTFILE
# /tmp/pscr-armbin -E /etc/passwd

PortShellCrypter [pscr] v0.65 (C) 2006-2022 stealth -- github.com/stealth/psc

begin-base64 600 /etc/passwd
YWRtaW46eDowOjA6cm9vdDovOi9iaW4vc2gK
====
# ###everlong###
 % cat script_/get_passwd 
unset HISTFILE
/tmp/pscr-armbin -E /etc/passwd
```

If the banner was gone, I could do something like `./pscsh -S scripting.socket -f script_/get_passwd | ./pscr -D > exfil/etc/passwd` more readily.

As is, I can put in some sed/awk magic, or interact with the scripting socket with Python, or comment out the prints for use, but it would make more sense to suppress the banner when pscr is being used purely as a text/file encoder/decoder.

**Comment by stealth** [comment]
Fixed in last push.
